config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users, only: [:index, :show, :edit, :update, :create, :destroy]
  resources :listings
  get 'relevant', to: 'listings#relevant'
  get 'favourites', to: 'listings#favourites'
  post 'favourites', to: 'listings#add_to_favourites'
  delete 'favourites/', to: 'listings#remove_favourite'
  get 'about', to: 'listings#about'
  get 'postcodes', to: 'listings#postcodes'
  get 'my_listings', to: 'listings#my_listings'
  post 'edit_postcodes', to: 'listings#edit_postcodes'
  
  # '
  # get 'listings/favourites', :to => 'listings#favourites'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :listing, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :listing, optional: true
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_one :address
  has_many :relevants
  has_many :favourites
  has_many :users, through: :favourites
  has_many :users, through: :relevants
  belongs_to :user, optional: true


  validates :description, :title, :landlord_name, :landlord_info, :landlord_phone, :landlord_email, :postcode, presence: true
  # date, :available,
  validates :title, uniqueness: true
  # validates :postcode, length: {maximum: 7}
  validates :landlord_phone, numericality: true

  def self.search(search)
    where("title LIKE ? OR description LIKE ? OR postcode LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :listing, optional: true
end

app/models/relevant.rb
class Relevant < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favourites
  has_many :relevants
  has_many :listings, through: :favourites
  has_many :listings, through: :relevants
  has_many :listings

  validates :first_name, :last_name, :phone, :email, :username, presence: true
  validates :phone, :email, :username, uniqueness: true
  validates :phone, numericality: true
  # åvalidates :password, length: {:within => 6..20}

  def send_mail
      UserMailer.welcome_email(self).deliver_now
  end

  after_create :send_mail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters

      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone, :username, :email])

      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone, :username])

    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
#add routes for favorites and relevants

  # before_action :locate_listing, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!, except: [:index]
  before_action :user_set

  def favourites
      @user = current_user
  end

  def my_listings
    @listings=Listing.where(user_id:current_user.id)
    render :index
  end

  def relevant
    @user = current_user
    @listings = Listing.all
  end

  def add_to_favourites
    @listing=Listing.find(params[:id])
    @favourite=Favourite.find_or_create_by(user: current_user, listing: @listing)
    #byebug
    if !current_user.favourites.include?(@favourite)
      @favourite.save
      redirect_to favourites_path
    else
      redirect_to favourites_path
    end
  end

  def remove_favourite
    @favourite=Favourite.find(params[:id])
    @favourite.destroy
    redirect_to favourites_path
  end

def postcodes
  @postcodes=current_user.relevants.map { |r| r.postcode}
  @relevant=Relevant.find_or_create_by(user_id: current_user.id)
end

def edit_postcodes
  @relevants=Relevant.where(user: current_user)
  @relevants.each do |r|
    r.delete
  end
 postcode_array = params[:postcodes].split(',').join(', ').split(', ')
  postcode_array.each do |postcode|
    Relevant.create(user_id: current_user.id, postcode: postcode)
  end
  redirect_to relevant_path
end

def index
@listings = Listing.all
if params[:search]
  @listings = Listing.search(params[:search]).order("created_at DESC")
else
  @listings = Listing.all.order("created_at DESC")
end
end

  def edit
     @listing=Listing.find(params[:id])
  end

  def show
     @listing=Listing.find(params[:id])
     @pictures=Picture.where(listing_id: @listing.id)
    # byebug
  end

  def update
     @listing=Listing.find(params[:id])
    @listing.update(listing_params)
    if @listing.valid?
      redirect_to listing_path
    else
      flash[:errors]=@listing.errors.full_messages
      redirect_to edit_listing_path
    end
  end

  def new
    @listing=Listing.new
  end

  def create
    @listing=Listing.new(listing_params)
    @listing.user=current_user
    if @listing.valid?
      @listing.save
      Picture.create(picture_url: listing_params[:picture_url], listing_id: @listing.id)
      redirect_to listing_path(@listing)
    else
      flash[:errors]=@listing.errors.full_messages
      redirect_to new_listing_path
    end
  end

  def destroy
    @listing=Listing.find(params[:id])
    @listing.delete
    redirect_to listings_path
    #do not let the user browse without an active advertisement
  end

  def about
    render :about
  end

  def new_pic
    @list_id =params[:id]
    @picture = Picture.new
  end



  private

  def user_set
    @user=current_user
  end

  def listing_params
    params.require(:listing).permit(:description, :title, :date, :landlord_name, :landlord_info, :landlord_phone, :landlord_email, :address_id, :picture_url, :id, :postcode, :postcodes)
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def create
    # byebug
    @picture=Picture.new
    @picture.picture_url=params[:picture][:picture_url]
    @picture.listing_id=params[:listing_id]
    # byebug
    @picture.save
    redirect_to listing_path(@picture.listing_id)
  end

  def show
    @picture=Picture.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    # before_action :locate_user, only: [:edit, :update, :show]

    def index
      if current_user

        redirect_to listings_path
      else
     render :layout => "carousel.html.erb"
      end
    end

    def new
      @user=User.new
    end

  def show
    # @user = User.find(params[:id])
    #we do not why but works
     # session.clear
     # redirect_to root_path
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.valid?
      redirect_to user_path
    else
      flash[:errors]=@user.errors.full_messages
      redirect_to edit_user_path
    end
  end

  def create
    @user=User.new(user_params)
    if @user.valid?
      redirect_to user_path
     else
       flash[:errors]=@user.errors.full_messages
       redirect_to new_user_path
    end

  end

  def delete
    session.clear
    redirect_to root_path
  end



  #login
  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone, :username, :password, :bio)
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/relevants_helper.rb
module RelevantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentTrader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <style>

    /* GENERAL STYLING */
     {
        box-sizing: border-box;
    }
    h4, h3, h2 {
      text-align: center;
    }

    .left_h4{
      text-align: left
    }
    hr {
      width: 95%
    }
    input, select, textarea {
      width: 100%; /* Full width */
      padding: 12px; /* Some padding */
      border: 1px solid #ccc; /* Gray border */
      border-radius: 4px; /* Rounded borders */
      box-sizing: border-box; /* Make sure that padding and width stays in place */
      margin-top: 6px; /* Add a top margin */
      margin-bottom: 16px; /* Bottom margin */
      resize: vertical /* Allow the user to vertically resize the textarea (not horizontally) */
    }


    body {
      background-color: #ddd;
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
    }

    footer {
      text-align: center;
      bottom: 10px;
    }



    .field {
      margin-right: 20px;
    }


/* IMAGES */

    img {
      background: #eee;
      border: 1px solid transparent;
      border-radius: 3px;
    }

  .sidenavimg{
      background: #eee;
      border: 1px solid #383838;
    }

    .sidenavimg:hover {
        background-color: #383838;
        color: black;
    }



    img:hover {
        background: #e1e1e1;
        border: 1px solid black;
    }


/* SEARCH BAR */

    .search-bar {
      align-items: center;
      margin-right: 18px;
    }
    .search-button {
      hidden;
    }


/* COLUMNS */
.d{
  s
}
    .column {
        float: left;
        width: 30%;
        margin-left: 2%;
        padding: 10px;
        height: 150px;
    }
    .column2 {
        text-align: center;
        float: left;
        width: 20%;
        padding: 10px;
        height: 150px;
    }
    .column3 {
        text-align: justify;
        float: left;
        width: 40%;
        padding: 10px;
        height: 150px;
    }


/* SIDENAV */

  .sidenav {
      height: 100%;
      width: 200px;
      position: fixed;
      z-index: 1;
      top: 0;
      left: 0;
      background-color: #383838;
      overflow-x: hidden;
  }

    .sidenav a {
        color: white;
        padding: 16px;
        display: block;
    }

    .sidenav a:hover {
        background-color: #ddd;
        color: black;
    }

    .content {
        margin-left: 200px;
        padding-left: 20px;
    }


    </style>
  </head>
  <body>



<div class="sidenav">
  <a href="<%= relevant_path %>"><img class="sidenavimg" src="<%=image_url('4.png')%>" style="width:160px;height:100px;" margin-right=0 alt="Recommendations page"></a>

<% if !user_signed_in? %>
<%= link_to "All listings", listings_path %>&nbsp&nbsp
<%= link_to "Sign Up", new_user_registration_path %>&nbsp &nbsp
<%= link_to "Log In", new_user_session_path %>&nbsp &nbsp
<% end %>

<% if user_signed_in? %>
<%= link_to "Favourites", favourites_path %>&nbsp &nbsp
<%= link_to "Browse all listings", listings_path %>&nbsp &nbsp
<%= link_to "Add a listing", new_listing_path %>&nbsp &nbsp
<%= link_to "The service explained", about_path %>&nbsp &nbsp
<%= link_to "My Postcodes of Interest", postcodes_path %>&nbsp &nbsp
<%= link_to "My listings", my_listings_path %>&nbsp &nbsp
<%= link_to current_user.username + "'s account settings", edit_user_registration_path %>&nbsp &nbsp
<%= link_to "Sign Out", destroy_user_session_path, method: "delete" %>&nbsp &nbsp
<%end%>

</div>
<div class="content">


<p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
     <div class="search-bar">

     <p><%= form_tag(listings_path, :method => "get", id: "search-form") do %></p>
         <%= text_field_tag :search, params[:search], placeholder: "Search" %>
         <p hidden ><%= submit_tag "Search", :name => nil %></p>
     <% end %>
   </div>
 <footer><br>
    <%= yield %>
     </div>

  </body>
</html>

app/views/layouts/carousel.html.erb
<%= yield %>

app/views/listings/_form.html.erb
 <%= form_for @listing do |l|   %>
   <%= l.label :title %><br>
   <%= l.text_field :title %><br>
   <%= l.label :description %><br>
   <%= l.text_area :description %><br>
   <%= l.label :landlord_name %><br>
   <%= l.text_field :landlord_name %><br>
   <%= l.label :landlord_email %><br>
   <%= l.text_field :landlord_email %><br>
   <%= l.label :landlord_phone %><br>
   <%= l.text_field :landlord_phone %><br>
   <%= l.label :landlord_info %><br>
   <%= l.text_field :landlord_info %><br>
   <%= l.label :postcode %><br>
   <%= l.text_field :postcode %><br>

   <%= l.submit 'Submit' %><br>
 <% end %>

app/views/listings/about.html.erb
<style>

p{
  text-align:justify;
  margin-right: 15%;
  margin-left: 15%;
}
</style>

<h5 align='center'>Welcome to Rent Trader!</h5><hr><br>

<p>Moving houses can be very stressful especially when you need to do it on short notice. If you think about it, when you are about to start renting a new place, you are very likely to end up in a place that somebody rented previously.<br><br>

Rent Trader is a service that addresses exactly that. Our web application allows you to switch places with a person that might be interested in moving to exactly your area. After registering you are able to see the listings and their location, current tenant and landlord contact information.<br><br>

The "Postcodes of interest" is a place where you specify the postcodes where you would be interested in moving to.<br><br>

You are welcome to browse listings or search by keywords, however our patent-pending "Recommended" page allows you to see the listings that are located in your postcodes of interest, so you are able to skip all the house offers that do not meet the criteria.<br><br>

You can also save listings to favourites if you would like to return back to them later.<br><br>

We hope that our web page will be the reason for your next move towards a better life.<br></p>

app/views/listings/edit.html.erb
<h4>Editing <%=@listing.title%> : </h4>
<%=  render 'form' %>

app/views/listings/favourites.html.erb
<% if @user.favourites.length>0 %>

<div><% @user.favourites.each do |l| %>
  <% pict = Picture.where(listing_id: l.listing.id).first %>
  <a href="<%= listing_path(l.listing) %>" class="column"><img src="<%= pict.picture_url%>" style="max-width:100%;max-height:100%;"> </a>
  <p class="column2"><%= link_to l.listing.title, listing_path(l.listing)  %><br><br><br><br>
  <%= link_to "Remove favourite", favourites_path(id: l.id), method: :delete %></p>
  <p class="column3"><%= l.listing.description %></p>
<br>
<% end %><br></div>
<% else %>
  <h5>You do not have any favourite listings yet.</h5>
<% end %>

app/views/listings/index.html.erb
<h2> Welcome to Rent Trader</h2>
<hr><br>
  <% @listings.each do |l| %>
  <% pict = Picture.where(listing_id: l.id).first %>
  <a href="<%= listing_path(l) %>" class="column"><img src="<%= pict.picture_url %>" style="max-width:100%;max-height:100%;"> </a>
  <p align="center" class="column2"><%= link_to l.title, listing_path(l) %></p>
  <p class="column3"><%= l.description %></p>

  <% end %>

app/views/listings/new.html.erb
<div text-color="red"><% if flash[:errors] %>
<% flash[:errors].each do |h|%>
<%= h %>
<% end %>
<% end %>
<h2> Add your new listing here!</h2><br><br></div>
<%= render 'form' %>

app/views/listings/new_pic.html.erb
<%= form_for @picture do |pic| %> 
  <%= pic.label "Add picture url:" %><br>
  <%= pic.text_field :picture_url %>
  <%= pic.button "Submit", name: "listing_id", value: @list_id %>

<% end %>

app/views/listings/postcodes.html.erb
<h4>Update your postcodes of interest here</h4>
<p> "Postcodes of interest" let the website recommend you the best listings based on the location you would like to move to. You are welcome to provide as many postcodes as you like, separated by a comma.</p>
<%= form_tag("/edit_postcodes", method: "post") do %>
  <%= label_tag(:postcodes, "Postcodes:") %><br>
  <%= text_field_tag :postcodes, (params[:postcodes] or @postcodes) %>
  <%= submit_tag("Change") %>
<% end %>

app/views/listings/relevant.html.erb
<h3>Recommended listings</h3><hr>

<% if @user.relevants.length > 0 %>
  <% @listings.each do |l| %>
    <% pict = Picture.where(listing_id: l.id).first %>
    <% @user.relevants.each do |relevant| %>
      <% if l.postcode[0..2].downcase == relevant.postcode[0..2].downcase or l.postcode.downcase == relevant.postcode.downcase or l.postcode[0..1].downcase == relevant.postcode[0..1].downcase%>
        <a href="<%= listing_path(l) %>" class="column"><img src="<%= pict.picture_url %>" style="max-width:100%;max-height:100%;"> </a>
        <p class="column2"><%= link_to l.title, listing_path(l) %></p>
        <p class="column3"><%= l.description %></p>

      <% end %>
    <% end %>
  <% end %>

<% end %>

app/views/listings/show.html.erb
<% require_relative "../../../config/api_key.rb"
%>

<style>
.description {
  text-align: center;
  width: 100%;
}
.map{
  margin-right: 2.5%;
}


</style>

<h2><%= @listing.title %></h2><hr><br>

<div>
<% @pictures.each do |pic| %>
  <a href="<%=picture_path(pic)%> "> <img src=" <%= pic.picture_url %> " style="max-width:40%;height:150px;"></a>
<% end %><br>
</div>

<div class="description">

<br><br>
<p>  <%= @listing.description %> </p><br>
<p> Postcode: <%= @listing.postcode %> </p><br>
<% if current_user==@listing.user %>
  <p><%= link_to "Add photo", "/new_picture/#{@listing.id}" %></p>
    <p><%= link_to "Edit listing", edit_listing_path(@listing) %></p>
  <p><%= link_to "Remove listing", listing_path(@listing), method: :delete %></p>
<% else %>
  <p><%= link_to 'Add to favourites', favourites_path(id: @listing.id), method: :post %></p>
<% end %>

</div>


<hr>
<div class="people_info">
<% if @listing.user %>
<h4>About the Tenant:<br></h4>
<% if @listing.user %>
<%= @listing.user.first_name + ' ' + @listing.user.last_name%><br>
<% if @listing.user.bio %><br><br>
Bio: <%=@listing.user.bio%><br>
<% end %>
<%= @listing.user.phone %><br>
<%= @listing.user.email %><br>

<% end %>
<%  else %>
<p> No information about the current tenant provided. <p>
<% end %>

<h4>About the Landlord:<br></h4>
Landlord: <%= @listing.landlord_name %><br>
About him/her: <%= @listing.landlord_info %><br>
Phone: <%= @listing.landlord_phone %><br>
Email: <%= @listing.landlord_email %>
<br><br>
</div>
<div class="map">

    <iframe width="100%" height="300" frameborder="0" style="border:0"  src="https://www.google.com/maps/embed/v1/place?q=<%= @listing.postcode %>&zoom=13&key=<%=KEY[:key]%>" allowfullscreen></iframe>


</div>

app/views/pictures/show.html.erb
<img src="<%= @picture.picture_url %>" style="max-width:100%;max-height:100%;"><br><br>
<button type="button"><%= link_to "Back", :back %></button>

app/views/users/index.html.erb
<style>  .carousel-inner img {
        width: 100%;
        margin: auto;
        height: 100%;
    }

</style><a href="<%=listings_path%>">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="3000" data-pause="false">

  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
       <%= image_tag("1.png") %>
    </div>

    <div class="item">
      <%= image_tag("2.png") %>
    </div>

    <div class="item">
      <%= image_tag("3.png") %>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</a>